version: "3"
services:
  api:
    build:
      context: ..
      dockerfile: ./cmd/api/Dockerfile
    platform: linux/{{platform}}
    entrypoint: ["./with-postgres.sh", "./api"]
    environment:
      - POSTGRES_USER=postgres # used only in with-postgres.sh
      - POSTGRES_PASSWORD=postgres # used only in with-postgres.sh
      - HTTP_PORT=8080
      - IMPL=mesa
      - DB_HOST=database
      - DB_POST=5432
      - DB_PASS=dev_password
      - DB_NAME=dev_database
      - DB_USER=dev_user
      - METRICS_PORT=9090
      - LOG_DEBUG=true
      - LOG_HUMAN=true
      - OTEL_SERVICE_NAME=tableland:api # this is just to the unknown_service from the metrics label
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:9090:9090"
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
  database:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    platform: linux/{{platform}}
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command:
      - "postgres"
      - "-c"
      - "compute_query_id=auto"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5