apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tableland-staging

resources:
- ../base

configMapGenerator:
- envs:
  - configApi.env
  name: configmap-api
- envs:
  - configHealthbot.env
  name: configmap-healthbot


patchesStrategicMerge:
- ingress-nginx-patch.yaml
images:
- name: tableland/api
  newName: LOLZ
